#Hanzala Siddiqui
#Computer Programming
#9/15/16
import turtle
wn=turtle.Screen()
hanz=turtle.Turtle()
hanz.speed(5)
wn.bgcolor("black")
hanz.pensize(10)
hanz.color("blue")
hanz.lt(180)
hanz.pu()
hanz.fd(180)
hanz.pd()
hanz.lt(180)
hanz.forward(150)
hanz.left(90)
hanz.color("red")
hanz.forward(150)
hanz.left(90)
hanz.color("orange")
hanz.forward(150)
hanz.left(90)
hanz.color("yellow")
hanz.forward(150)
hanz.left(90)

tess = turtle.Turtle()
josh = turtle.Turtle()
josh.color("blue")              
tess.color("red")
josh.pensize(35) 
tess.pensize(50)                

tess.forward(150)
tess.left(120)
tess.color("pink")
tess.forward(150)
tess.left(120)
tess.color("purple")
tess.forward(150)
tess.left(120)
tess.pu()

josh.left(40)
josh.pu()
josh.fd(40)
josh.rt(40)
josh.fd(15)
josh.pd()
josh.fd(60)
josh.lt(120)
josh.fd(60)
josh.lt(120)
josh.fd(60)
josh.pu()
